### ISSUE TITLE
How to configure yolov5-seg?

### ISSUE THREAD

**Issue by Anleeno-Xu** [vietanhdev/anylabeling#146]
I have made a yaml file and loaded a yolov5-seg model, but the labeling results are just boxes (just few images have results).

```yaml
type: yolov5
name: yolov5n-seg
display_name: YOLOv5n-seg
model_path: y5n_seg.onnx
confidence_threshold: 0.25
input_height: 640
input_width: 640
nms_threshold: 0.45
score_threshold: 0.5
classes:
  - a
  - b
```
